language: python
# whitelist
branches:
  only:
    - master

python:
    - 2.7

env:
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=py36
  - TOX_ENV=pypy
  - TOX_ENV=flake
  - TOX_ENV=cover

install:
    - pip install --default-timeout 60 tox

script:
    - tox -e $TOX_ENV

after_script:
  - if [ $TOX_ENV == "cover" ]; then
    pip install --quiet coveralls;
    coveralls;
    fi
