language: python

python:
  - 2.7

before_install:
- pip install --default-timeout 60 tox
# Travis-CI apparently has this built-in and no upgrade is done when our setup runs
- pip install --upgrade pytest>=3.4.0 

jobs:
    include:
        - python:
            - 3.4
          script: tox -e flake
        - python:
            - 2.7
          script: tox -e py27
        - python:
            - 3.4
          script: tox -e py34
        - python:
            - 3.6
          script: tox -e py36
        - install: pip install --quiet --default-timeout 60 coveralls
          script: tox -e cover
          after_script: coveralls
