language: python
# whitelist
branches:
  only:
    - master

python:
    - 2.7

env:
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=flake

install:
    - pip install --default-timeout 60 tox

script:
    - tox -e $TOX_ENV

jobs:
    include:
        - stage: py36
          python:
              - 3.6
          script: tox -e py36
        - stage: coverage
          install: pip install --quiet coveralls
          script: tox -e coverage
          after_script: coveralls
            fi
